// ══════════════════════════════════════════════════════════════════
// NYC DREAM 2.0 — DATA.JS
// All static game data: locations, jobs, items, events, stocks, etc.
// ══════════════════════════════════════════════════════════════════

// ── NYC LOCATIONS (110+ spots) ─────────────────────────────────────
const NYC_LOCATIONS = [
  // ── LOWER MANHATTAN ──
  { name:"Battery Park",          x:520,  y:700, type:"PUBLIC PARK",       icon:"🌿", color:"#00933C", borough:"Manhattan" },
  { name:"Staten Island Ferry",   x:506,  y:709, type:"TRANSIT / LANDMARK",icon:"⛴️", color:"#0039A6", borough:"Manhattan" },
  { name:"Wall Street",           x:540,  y:662, type:"FINANCE DISTRICT",  icon:"📈", color:"#C4A35A", borough:"Manhattan" },
  { name:"New York Stock Exchange",x:538, y:660, type:"FINANCE",           icon:"🏛️", color:"#C4A35A", borough:"Manhattan" },
  { name:"World Trade Center",    x:515,  y:660, type:"LANDMARK / OFFICE", icon:"🗼", color:"#333",    borough:"Manhattan" },
  { name:"Fulton Center",         x:548,  y:651, type:"TRANSIT HUB",       icon:"🚇", color:"#0039A6", borough:"Manhattan" },
  { name:"City Hall",             x:548,  y:640, type:"GOVERNMENT",        icon:"🏛️", color:"#555",    borough:"Manhattan" },
  { name:"Brooklyn Bridge Park",  x:580,  y:669, type:"PARK / WATERFRONT", icon:"🌉", color:"#00933C", borough:"Manhattan" },
  { name:"South Street Seaport",  x:566,  y:675, type:"TOURIST / MARKET",  icon:"⚓", color:"#0039A6", borough:"Manhattan" },
  { name:"Chinatown",             x:556,  y:632, type:"FOOD / CULTURE",    icon:"🏮", color:"#E8001A", borough:"Manhattan" },
  { name:"Little Italy",          x:553,  y:621, type:"FOOD / CULTURE",    icon:"🍕", color:"#009246", borough:"Manhattan" },
  { name:"Tribeca",               x:530,  y:620, type:"ARTS / RESIDENTIAL",icon:"🎨", color:"#8B00FF", borough:"Manhattan" },
  { name:"SoHo",                  x:538,  y:605, type:"SHOPPING / ART",    icon:"🛍️", color:"#8B00FF", borough:"Manhattan" },
  { name:"Katz's Delicatessen",   x:558,  y:598, type:"ICONIC RESTAURANT", icon:"🥪", color:"#E8001A", borough:"Manhattan" },
  { name:"Lower East Side",       x:564,  y:608, type:"NIGHTLIFE / FOOD",  icon:"🍺", color:"#8B4513", borough:"Manhattan" },
  { name:"Financial District",    x:530,  y:655, type:"BUSINESS / FINANCE",icon:"💼", color:"#C4A35A", borough:"Manhattan" },
  // ── MIDTOWN & VILLAGES ──
  { name:"Greenwich Village",     x:519,  y:585, type:"BOHEMIAN / FOOD",   icon:"🎸", color:"#8B4513", borough:"Manhattan" },
  { name:"West Village",          x:506,  y:578, type:"UPSCALE VILLAGE",   icon:"🌺", color:"#C4A35A", borough:"Manhattan" },
  { name:"Meatpacking District",  x:504,  y:565, type:"NIGHTLIFE / LUXURY",icon:"🍾", color:"#8B00FF", borough:"Manhattan" },
  { name:"High Line Park",        x:490,  y:555, type:"ELEVATED PARK",     icon:"🌿", color:"#00933C", borough:"Manhattan" },
  { name:"Chelsea",               x:483,  y:558, type:"ARTS / RESIDENTIAL",icon:"🖼️", color:"#8B00FF", borough:"Manhattan" },
  { name:"Chelsea Market",        x:485,  y:563, type:"FOOD MARKET",       icon:"🥐", color:"#8B4513", borough:"Manhattan" },
  { name:"Flatiron Building",     x:537,  y:522, type:"LANDMARK / OFFICE", icon:"🏗️", color:"#555",    borough:"Manhattan" },
  { name:"Madison Square Park",   x:537,  y:517, type:"PUBLIC PARK",       icon:"🌳", color:"#00933C", borough:"Manhattan" },
  { name:"Gramercy Park",         x:558,  y:540, type:"RESIDENTIAL",       icon:"🌺", color:"#00933C", borough:"Manhattan" },
  { name:"Stuyvesant Town",       x:568,  y:557, type:"RESIDENTIAL",       icon:"🏘️", color:"#555",    borough:"Manhattan" },
  { name:"Union Square",          x:538,  y:535, type:"PLAZA / MARKET",    icon:"🎭", color:"#FF6319", borough:"Manhattan" },
  { name:"14th Street",           x:520,  y:570, type:"TRANSIT CORRIDOR",  icon:"🚇", color:"#0039A6", borough:"Manhattan" },
  { name:"Madison Square Garden", x:480,  y:511, type:"ARENA / EVENTS",    icon:"🏟️", color:"#FF6319", borough:"Manhattan" },
  { name:"Penn Station",          x:480,  y:521, type:"TRANSIT HUB",       icon:"🚂", color:"#0039A6", borough:"Manhattan" },
  { name:"Herald Square",         x:494,  y:513, type:"SHOPPING / TRANSIT",icon:"🛒", color:"#555",    borough:"Manhattan" },
  { name:"Macy's 34th Street",    x:490,  y:510, type:"RETAIL",            icon:"🏬", color:"#E8001A", borough:"Manhattan" },
  { name:"Empire State Building", x:502,  y:506, type:"LANDMARK",          icon:"🏙️", color:"#C4A35A", borough:"Manhattan" },
  { name:"Bryant Park",           x:534,  y:487, type:"PUBLIC PARK",       icon:"🌳", color:"#00933C", borough:"Manhattan" },
  { name:"Times Square",          x:510,  y:482, type:"ENTERTAINMENT",     icon:"🎭", color:"#FF6319", borough:"Manhattan" },
  { name:"Grand Central Terminal",x:567,  y:490, type:"TRANSIT HUB",       icon:"🚆", color:"#0039A6", borough:"Manhattan" },
  { name:"Chrysler Building",     x:571,  y:487, type:"LANDMARK / OFFICE", icon:"🏢", color:"#C4A35A", borough:"Manhattan" },
  { name:"United Nations",        x:597,  y:484, type:"GOVERNMENT / INTL", icon:"🌐", color:"#0039A6", borough:"Manhattan" },
  { name:"Rockefeller Center",    x:555,  y:453, type:"OFFICE / MEDIA",    icon:"🏢", color:"#555",    borough:"Manhattan" },
  { name:"5th Avenue Shopping",   x:575,  y:432, type:"LUXURY SHOPPING",   icon:"💎", color:"#C4A35A", borough:"Manhattan" },
  { name:"Radio City Music Hall", x:553,  y:456, type:"ENTERTAINMENT",     icon:"🎪", color:"#FF6319", borough:"Manhattan" },
  { name:"Carnegie Hall",         x:540,  y:461, type:"CONCERT HALL",      icon:"🎻", color:"#C4A35A", borough:"Manhattan" },
  { name:"Hell's Kitchen",        x:465,  y:472, type:"FOOD / RESIDENTIAL",icon:"🍽️", color:"#E8001A", borough:"Manhattan" },
  { name:"Port Authority",        x:462,  y:481, type:"TRANSIT HUB",       icon:"🚌", color:"#0039A6", borough:"Manhattan" },
  { name:"Midtown East",          x:578,  y:470, type:"BUSINESS DISTRICT", icon:"🏢", color:"#555",    borough:"Manhattan" },
  // ── UPPER MANHATTAN ──
  { name:"Central Park South",    x:540,  y:430, type:"LUXURY / HOTEL",    icon:"🏨", color:"#C4A35A", borough:"Manhattan" },
  { name:"Central Park",          x:548,  y:375, type:"PUBLIC PARK",       icon:"🌲", color:"#00933C", borough:"Manhattan" },
  { name:"Strawberry Fields",     x:508,  y:380, type:"PARK / MEMORIAL",   icon:"✌️", color:"#00933C", borough:"Manhattan" },
  { name:"The Plaza Hotel",       x:556,  y:432, type:"LUXURY HOTEL",      icon:"👑", color:"#C4A35A", borough:"Manhattan" },
  { name:"Museum of Nat. History", x:503, y:360, type:"MUSEUM",            icon:"🦕", color:"#004F9E", borough:"Manhattan" },
  { name:"Upper West Side",       x:498,  y:352, type:"RESIDENTIAL",       icon:"🏘️", color:"#555",    borough:"Manhattan" },
  { name:"Lincoln Center",        x:501,  y:426, type:"ARTS / PERFORMANCE",icon:"🎼", color:"#004F9E", borough:"Manhattan" },
  { name:"Metropolitan Museum",   x:616,  y:359, type:"MUSEUM",            icon:"🖼️", color:"#004F9E", borough:"Manhattan" },
  { name:"Upper East Side",       x:618,  y:356, type:"LUXURY RESIDENTIAL",icon:"🏰", color:"#C4A35A", borough:"Manhattan" },
  { name:"Guggenheim Museum",     x:614,  y:340, type:"MUSEUM",            icon:"🌀", color:"#004F9E", borough:"Manhattan" },
  { name:"Harlem",                x:552,  y:292, type:"CULTURE / MUSIC",   icon:"🎷", color:"#8B4513", borough:"Manhattan" },
  { name:"Apollo Theater",        x:543,  y:285, type:"ENTERTAINMENT",     icon:"🎤", color:"#E8001A", borough:"Manhattan" },
  { name:"125th Street",          x:548,  y:278, type:"SHOPPING / TRANSIT",icon:"🛒", color:"#555",    borough:"Manhattan" },
  { name:"Columbia University",   x:521,  y:265, type:"EDUCATION",         icon:"🎓", color:"#004F9E", borough:"Manhattan" },
  { name:"Morningside Heights",   x:512,  y:272, type:"RESIDENTIAL",       icon:"🏘️", color:"#555",    borough:"Manhattan" },
  { name:"Washington Heights",    x:528,  y:222, type:"RESIDENTIAL",       icon:"🏠", color:"#555",    borough:"Manhattan" },
  { name:"Inwood",                x:522,  y:195, type:"RESIDENTIAL / PARK",icon:"🌳", color:"#00933C", borough:"Manhattan" },
  { name:"The Bronx GW Bridge",   x:461,  y:216, type:"LANDMARK / BRIDGE", icon:"🌉", color:"#8B4513", borough:"Manhattan" },
  // ── BROOKLYN ──
  { name:"Williamsburg",          x:660,  y:580, type:"HIPSTER / FOOD",    icon:"🍺", color:"#8B4513", borough:"Brooklyn" },
  { name:"DUMBO",                 x:623,  y:642, type:"TECH / ARTS",       icon:"💻", color:"#0066FF", borough:"Brooklyn" },
  { name:"Brooklyn Heights",      x:606,  y:658, type:"UPSCALE RESIDENTIAL",icon:"🏡",color:"#C4A35A", borough:"Brooklyn" },
  { name:"Downtown Brooklyn",     x:633,  y:671, type:"BUSINESS / COURT",  icon:"🏢", color:"#555",    borough:"Brooklyn" },
  { name:"Barclay's Center",      x:635,  y:676, type:"SPORTS ARENA",      icon:"🏀", color:"#000",    borough:"Brooklyn" },
  { name:"Park Slope",            x:600,  y:703, type:"FAMILY / PARKS",    icon:"🏡", color:"#555",    borough:"Brooklyn" },
  { name:"Prospect Park",         x:610,  y:718, type:"PUBLIC PARK",       icon:"🌲", color:"#00933C", borough:"Brooklyn" },
  { name:"Crown Heights",         x:644,  y:722, type:"RESIDENTIAL",       icon:"🏘️", color:"#555",    borough:"Brooklyn" },
  { name:"Flatbush",              x:650,  y:751, type:"RESIDENTIAL",       icon:"🏠", color:"#555",    borough:"Brooklyn" },
  { name:"Bushwick",              x:678,  y:618, type:"ARTS / NIGHTLIFE",  icon:"🎨", color:"#8B00FF", borough:"Brooklyn" },
  { name:"Greenpoint",            x:665,  y:545, type:"RESIDENTIAL / FOOD",icon:"🌿", color:"#555",    borough:"Brooklyn" },
  { name:"Red Hook",              x:596,  y:686, type:"INDUSTRIAL / ARTSY",icon:"⚓", color:"#8B4513", borough:"Brooklyn" },
  { name:"Bay Ridge",             x:602,  y:768, type:"RESIDENTIAL",       icon:"🏡", color:"#555",    borough:"Brooklyn" },
  { name:"Coney Island",          x:641,  y:805, type:"BEACH / AMUSEMENT", icon:"🎡", color:"#FF6319", borough:"Brooklyn" },
  { name:"Brighton Beach",        x:667,  y:808, type:"BEACH / CULTURE",   icon:"🏖️", color:"#0039A6", borough:"Brooklyn" },
  { name:"Sunset Park",           x:610,  y:738, type:"RESIDENTIAL",       icon:"🌅", color:"#555",    borough:"Brooklyn" },
  { name:"Fort Greene",           x:636,  y:661, type:"ARTS / RESIDENTIAL",icon:"🌿", color:"#555",    borough:"Brooklyn" },
  // ── QUEENS ──
  { name:"Long Island City",      x:629,  y:494, type:"ARTS / BUSINESS",   icon:"🏗️", color:"#555",    borough:"Queens" },
  { name:"Astoria",               x:641,  y:440, type:"FOOD / RESIDENTIAL",icon:"🍽️", color:"#8B4513", borough:"Queens" },
  { name:"Jackson Heights",       x:706,  y:500, type:"DIVERSE / FOOD",    icon:"🌶️", color:"#E8001A", borough:"Queens" },
  { name:"Flushing",              x:779,  y:462, type:"ASIAN CULTURE",     icon:"🥟", color:"#E8001A", borough:"Queens" },
  { name:"Citi Field",            x:745,  y:466, type:"BASEBALL STADIUM",  icon:"⚾", color:"#FF6319", borough:"Queens" },
  { name:"Arthur Ashe Stadium",   x:752,  y:471, type:"TENNIS STADIUM",    icon:"🎾", color:"#0066FF", borough:"Queens" },
  { name:"Forest Hills",          x:728,  y:546, type:"RESIDENTIAL",       icon:"🌲", color:"#555",    borough:"Queens" },
  { name:"Jamaica",               x:768,  y:572, type:"TRANSIT / BUSINESS",icon:"🚌", color:"#555",    borough:"Queens" },
  { name:"Far Rockaway",          x:806,  y:634, type:"BEACH / RESIDENTIAL",icon:"🌊",color:"#0039A6", borough:"Queens" },
  { name:"JFK Airport",           x:791,  y:624, type:"AIRPORT",           icon:"✈️", color:"#0066FF", borough:"Queens" },
  { name:"LaGuardia Airport",     x:686,  y:422, type:"AIRPORT",           icon:"✈️", color:"#0066FF", borough:"Queens" },
  // ── THE BRONX ──
  { name:"South Bronx",           x:596,  y:272, type:"RESIDENTIAL",       icon:"🏘️", color:"#555",    borough:"Bronx" },
  { name:"Yankee Stadium",        x:601,  y:272, type:"SPORTS ARENA",      icon:"⚾", color:"#003087", borough:"Bronx" },
  { name:"Arthur Avenue",         x:636,  y:262, type:"ITALIAN FOOD",      icon:"🍝", color:"#009246", borough:"Bronx" },
  { name:"Fordham University",    x:634,  y:250, type:"EDUCATION",         icon:"🎓", color:"#8B0000", borough:"Bronx" },
  { name:"Bronx Zoo",             x:650,  y:248, type:"ZOO / NATURE",      icon:"🦁", color:"#228B22", borough:"Bronx" },
  { name:"New York Botanical Garden",x:658,y:236,type:"NATURE / PARK",     icon:"🌸", color:"#00933C", borough:"Bronx" },
  { name:"City Island",           x:700,  y:200, type:"SEAFOOD / UNIQUE",  icon:"🦞", color:"#0039A6", borough:"Bronx" },
  { name:"Co-op City",            x:690,  y:218, type:"RESIDENTIAL",       icon:"🏢", color:"#555",    borough:"Bronx" },
  { name:"Pelham Bay Park",       x:715,  y:208, type:"PUBLIC PARK",       icon:"🌲", color:"#00933C", borough:"Bronx" },
  // ── STATEN ISLAND ──
  { name:"St. George Ferry",      x:476,  y:738, type:"TRANSIT / FERRY",   icon:"⛴️", color:"#0039A6", borough:"Staten Island" },
  { name:"Snug Harbor",           x:452,  y:728, type:"CULTURE / PARK",    icon:"🏛️", color:"#004F9E", borough:"Staten Island" },
  { name:"Staten Island Mall",    x:432,  y:752, type:"SHOPPING",          icon:"🏬", color:"#555",    borough:"Staten Island" },
  { name:"Verrazzano Bridge",     x:578,  y:782, type:"LANDMARK / BRIDGE", icon:"🌉", color:"#8B4513", borough:"Staten Island" },
  { name:"Tottenville",           x:395,  y:808, type:"RESIDENTIAL",       icon:"🏡", color:"#555",    borough:"Staten Island" },
];

// ── ROAD DATA ──────────────────────────────────────────────────────
const ROAD_DATA = {
  // Manhattan avenues (N-S lines)
  avenues: [
    { name:"12th Ave / West Side Hwy", x:464, y1:210, y2:710, major:true  },
    { name:"11th Ave",                 x:472, y1:260, y2:590, major:false },
    { name:"10th Ave",                 x:480, y1:260, y2:590, major:true  },
    { name:"9th Ave / Columbus",       x:488, y1:260, y2:600, major:false },
    { name:"8th Ave / CPW",            x:496, y1:210, y2:600, major:true  },
    { name:"7th Ave / FashionAve",     x:503, y1:240, y2:605, major:true  },
    { name:"6th Ave / Ave Americas",   x:514, y1:240, y2:605, major:true  },
    { name:"5th Ave",                  x:524, y1:210, y2:610, major:true  },
    { name:"Madison Ave",              x:534, y1:240, y2:520, major:true  },
    { name:"Park Ave",                 x:543, y1:240, y2:510, major:true  },
    { name:"Lexington Ave",            x:552, y1:240, y2:510, major:false },
    { name:"3rd Ave",                  x:560, y1:240, y2:570, major:true  },
    { name:"2nd Ave",                  x:569, y1:240, y2:595, major:false },
    { name:"1st Ave",                  x:578, y1:240, y2:615, major:true  },
    { name:"York Ave",                 x:588, y1:300, y2:440, major:false },
    { name:"FDR Drive",                x:596, y1:240, y2:700, major:true  },
  ],
  // Manhattan cross streets (E-W)
  streets: [
    { name:"Chambers",  y:640, label:true  },
    { name:"Canal",     y:626, label:true  },
    { name:"Houston",   y:598, label:true  },
    { name:"14th St",   y:572, label:true  },
    { name:"23rd St",   y:551, label:true  },
    { name:"34th St",   y:529, label:true  },
    { name:"42nd St",   y:511, label:true  },
    { name:"57th St",   y:487, label:true  },
    { name:"72nd St",   y:463, label:true  },
    { name:"79th St",   y:451, label:false },
    { name:"86th St",   y:439, label:true  },
    { name:"96th St",   y:423, label:true  },
    { name:"110th St",  y:401, label:true  },
    { name:"116th St",  y:390, label:false },
    { name:"125th St",  y:378, label:true  },
    { name:"135th St",  y:358, label:false },
    { name:"145th St",  y:338, label:true  },
    { name:"155th St",  y:318, label:false },
    { name:"168th St",  y:291, label:true  },
    { name:"181st St",  y:264, label:true  },
    { name:"190th St",  y:244, label:false },
    { name:"207th St",  y:216, label:true  },
  ],
  // Highways
  highways: [
    { name:"FDR Drive",           color:"#2255AA", width:3,
      points:[[597,700],[597,682],[598,660],[597,640],[598,620],[597,600],[597,580],[598,560],[597,540],[597,520],[598,500],[597,480],[597,460],[598,440],[597,420],[597,400],[597,380],[597,360],[597,330],[597,300],[597,270],[597,240]] },
    { name:"West Side Hwy",       color:"#2255AA", width:3,
      points:[[464,700],[464,680],[463,655],[464,630],[463,600],[464,580],[463,555],[464,530],[463,505],[464,480],[463,455],[464,430],[463,400],[464,360],[463,320],[462,280],[461,240],[460,215]] },
    { name:"Henry Hudson Pkwy",   color:"#2255AA", width:3,
      points:[[460,215],[459,195]] },
    { name:"BQE",                 color:"#BB4400", width:3,
      points:[[614,670],[620,650],[624,630],[622,600],[618,570],[615,540],[618,510],[620,490]] },
    { name:"LIE / I-495",         color:"#BB4400", width:3,
      points:[[620,490],[660,490],[700,485],[740,478],[780,470],[810,465]] },
    { name:"Belt Parkway",        color:"#228833", width:3,
      points:[[578,780],[590,776],[610,770],[630,770],[654,762],[672,752],[692,740],[708,730],[720,720],[726,700],[730,680],[732,660],[800,640],[808,625]] },
    { name:"Cross Bronx Expy",    color:"#BB6600", width:3,
      points:[[460,218],[490,222],[520,226],[550,228],[580,232],[610,236],[640,236],[668,234],[698,228]] },
    { name:"Bruckner Blvd",       color:"#BB6600", width:2,
      points:[[620,280],[640,270],[660,260],[680,250],[700,240],[718,232]] },
    { name:"Staten Island Expy",  color:"#884400", width:2,
      points:[[578,782],[550,774],[520,762],[500,756],[476,744],[455,738]] },
    { name:"Gowanus Expy",        color:"#BB4400", width:2,
      points:[[578,782],[586,770],[596,756],[600,738],[602,720],[606,700],[610,686]] },
    { name:"Brooklyn-Queens Expy",color:"#BB4400", width:2,
      points:[[620,490],[624,510],[620,530],[616,554],[614,575],[616,596],[618,610],[616,628],[614,648],[614,668]] },
    { name:"Grand Central Pkwy",  color:"#664400", width:2,
      points:[[690,424],[710,430],[730,436],[752,445],[770,454],[786,462]] },
    { name:"Van Wyck Expy",       color:"#664400", width:2,
      points:[[786,462],[790,490],[790,520],[790,560],[792,592],[792,620]] },
  ],
  // Bike lanes
  bikeLanes: [
    { name:"Hudson River Greenway",color:"#00C853",
      points:[[464,700],[464,680],[463,655],[464,630],[463,600],[464,580],[463,555],[464,530],[463,505],[464,480],[463,455],[464,430],[463,400],[464,360],[463,320],[462,280],[461,240]] },
    { name:"1st Ave Bike Lane",   color:"#00C853",
      points:[[578,598],[578,580],[578,560],[578,540],[578,520],[578,500],[578,480],[578,460],[578,440],[578,420],[578,400],[578,380]] },
    { name:"2nd Ave Bike Lane",   color:"#00C853",
      points:[[569,590],[569,572],[569,552],[569,530],[569,512],[569,490],[569,470],[569,450],[569,430],[569,410],[569,388]] },
    { name:"9th Ave / CPW Lane",  color:"#00C853",
      points:[[488,598],[488,580],[488,560],[488,540],[488,520],[488,500],[496,475],[498,450],[498,420],[497,390],[497,360]] },
    { name:"Brooklyn Bridge",     color:"#00C853",
      points:[[518,668],[540,660],[562,652],[578,650]] },
    { name:"Brooklyn Waterfront", color:"#00C853",
      points:[[578,650],[596,666],[610,680],[614,700],[614,720]] },
  ],
  // Major Queens/Brooklyn avenues
  outerAvenues: [
    { name:"Atlantic Ave",    points:[[612,672],[634,674],[654,674],[676,672],[696,668],[716,664]], color:"#555" },
    { name:"Eastern Pkwy",    points:[[634,676],[654,680],[674,680],[694,678],[712,676]], color:"#555" },
    { name:"Flatbush Ave",    points:[[614,668],[620,692],[622,714],[624,732],[626,752],[626,770]], color:"#888" },
    { name:"Bedford Ave",     points:[[660,580],[658,600],[656,620],[656,640],[656,660],[658,680],[660,700]], color:"#888" },
    { name:"Queens Blvd",     points:[[626,494],[648,500],[670,508],[692,512],[712,518],[732,524],[752,532]], color:"#888" },
    { name:"Northern Blvd",   points:[[630,452],[652,446],[672,442],[694,438],[714,434],[734,430],[754,426],[774,420]], color:"#888" },
    { name:"Jamaica Ave",     points:[[680,540],[700,538],[720,538],[740,540],[760,542],[778,548]], color:"#888" },
    { name:"Grand Concourse", points:[[598,282],[604,268],[610,254],[618,238],[624,224],[628,210]], color:"#888" },
  ],
};

// ── SUBWAY LINES ────────────────────────────────────────────────────
const SUBWAY_LINES = [
  { name:"A/C/E",  color:"#0039A6", width:2.5,
    points:[[520,700],[525,680],[522,660],[518,640],[520,618],[524,596],[520,572],[500,555],[490,538],[484,522],[480,505],[478,488],[476,465],[476,440],[480,414],[488,392],[490,366],[494,342],[494,318],[496,296],[500,270],[506,244],[514,222],[516,198]] },
  { name:"B/D/F/M",color:"#FF6319", width:2.5,
    points:[[640,802],[640,780],[638,758],[636,736],[634,712],[630,688],[620,666],[610,646],[600,622],[592,600],[580,576],[564,556],[548,534],[536,514],[520,495],[510,474],[504,454],[500,432],[498,408],[498,382],[496,356],[494,332],[492,308],[490,286],[492,264],[494,240]] },
  { name:"4/5/6",  color:"#00933C", width:2.5,
    points:[[567,490],[566,510],[564,530],[562,550],[560,570],[560,594],[558,618],[556,634],[552,650],[548,666],[546,684],[546,698]] },
  { name:"1/2/3",  color:"#EE352E", width:2.5,
    points:[[601,272],[598,292],[596,312],[594,332],[592,356],[590,380],[588,404],[586,428],[584,448],[582,464],[576,476],[566,484],[556,490],[548,494],[538,500],[526,506],[514,512],[504,520],[498,534],[494,548],[490,562],[488,578],[488,596],[490,614],[490,634],[494,652],[496,670],[496,688],[498,706]] },
  { name:"N/Q/R/W",color:"#FCCC0A", width:2.5,
    points:[[779,462],[756,464],[734,466],[714,468],[694,472],[674,476],[654,480],[634,484],[614,484],[596,486],[578,488],[562,490],[548,490],[538,492],[524,494],[512,498],[502,504],[494,512],[488,520],[482,530],[478,544],[476,558],[476,574],[476,590],[476,608],[478,628],[480,650],[482,672]] },
  { name:"J/Z",    color:"#996633", width:2,
    points:[[548,666],[560,658],[572,650],[586,642],[600,632],[616,620],[630,608],[646,592],[660,578],[672,564],[680,548],[686,534],[690,520],[694,506],[696,492]] },
  { name:"7",      color:"#B933AD", width:2,
    points:[[556,490],[570,492],[586,492],[602,492],[618,492],[636,490],[652,488],[666,486],[680,484],[694,482],[706,478],[720,474],[736,470],[752,466],[766,462]] },
  { name:"G",      color:"#6CBE45", width:2,
    points:[[548,490],[554,504],[560,518],[562,534],[560,550],[558,566],[558,582],[560,598],[562,614],[562,630],[560,648],[556,664],[552,678],[546,690]] },
  { name:"L",      color:"#A7A9AC", width:2,
    points:[[480,570],[500,568],[520,566],[540,566],[560,568],[580,568],[602,566],[622,562],[642,558],[660,556]] },
  { name:"S/Shuttle",color:"#808183", width:2,
    points:[[548,490],[556,490],[564,490],[572,490],[578,490],[584,490]] },
];

// ── BRIDGES ─────────────────────────────────────────────────────────
const BRIDGES = [
  { name:"Brooklyn Bridge",    p1:[580,669], p2:[614,658], color:"#8B4513", width:4 },
  { name:"Manhattan Bridge",   p1:[573,645], p2:[610,640], color:"#666",    width:3 },
  { name:"Williamsburg Bridge",p1:[575,616], p2:[618,612], color:"#666",    width:3 },
  { name:"Queensboro Bridge",  p1:[614,455], p2:[640,455], color:"#8B4513", width:4 },
  { name:"GW Bridge",          p1:[461,216], p2:[435,214], color:"#8B4513", width:5 },
  { name:"Verrazzano Bridge",  p1:[579,784], p2:[596,786], color:"#8B4513", width:4 },
  { name:"Triborough/RFK",     p1:[612,448], p2:[635,428], color:"#666",    width:3 },
  { name:"Hell Gate Bridge",   p1:[608,426], p2:[626,418], color:"#666",    width:2 },
  { name:"Throggs Neck Bridge",p1:[716,216], p2:[718,200], color:"#666",    width:2 },
  { name:"Whitestone Bridge",  p1:[734,210], p2:[736,196], color:"#666",    width:2 },
  { name:"Outerbridge",        p1:[410,806], p2:[395,810], color:"#666",    width:2 },
  { name:"Bayonne Bridge",     p1:[432,758], p2:[416,758], color:"#666",    width:2 },
];

// ── JOBS DATABASE (30+ jobs, unlimited rating tiers) ───────────────
const JOBS = [
  // Entry Level (0–50 rep)
  { id:"homeless_performer", title:"STREET PERFORMER",    location:"Times Square",      pay:40,   minRating:0,   icon:"🎸", dept:"arts",    taskType:"click", desc:"Play for tips in Times Square. Click audience members as they walk by!" },
  { id:"dishwasher",         title:"DISHWASHER",          location:"Little Italy",       pay:80,   minRating:0,   icon:"🍽️", dept:"food",    taskType:"click", desc:"Scrub through the dinner rush. Click dirty plates before they stack up!" },
  { id:"delivery",           title:"DELIVERY CYCLIST",    location:"Greenwich Village",  pay:95,   minRating:0,   icon:"🚴", dept:"transit",  taskType:"click", desc:"Pedal deliveries. Hit all packages before time runs out!" },
  { id:"hotdog",             title:"HOT DOG VENDOR",      location:"Central Park",       pay:115,  minRating:10,  icon:"🌭", dept:"food",    taskType:"click", desc:"Serve park tourists. Click customers before they walk away!" },
  { id:"newsstand",          title:"NEWSSTAND CLERK",     location:"Penn Station",       pay:90,   minRating:0,   icon:"📰", dept:"retail",  taskType:"click", desc:"Sell papers and snacks to commuters. Move fast!" },
  { id:"parking_attendant",  title:"PARKING ATTENDANT",   location:"Midtown East",       pay:100,  minRating:5,   icon:"🅿️", dept:"transit", taskType:"click", desc:"Park cars fast. Don't scratch anything!" },
  // Skilled (50–100 rep)
  { id:"barista",            title:"BARISTA",             location:"SoHo",               pay:135,  minRating:25,  icon:"☕", dept:"food",    taskType:"click", desc:"Brew coffee for the SoHo crowd. Match orders quick!" },
  { id:"bodyguard",          title:"CLUB BOUNCER",        location:"Chelsea",            pay:165,  minRating:30,  icon:"🛡️", dept:"security",taskType:"click", desc:"Keep the line moving. Spot troublemakers before they cause issues!" },
  { id:"retail",             title:"RETAIL ASSOCIATE",    location:"5th Avenue Shopping",pay:185,  minRating:35,  icon:"🛍️", dept:"retail",  taskType:"click", desc:"Upsell luxury goods. Read customers perfectly!" },
  { id:"mailroom",           title:"MAILROOM CLERK",      location:"Rockefeller Center", pay:205,  minRating:40,  icon:"📬", dept:"office",  taskType:"click", desc:"Sort packages before the truck leaves!" },
  { id:"driver",             title:"CAB / RIDESHARE DRIVER",location:"Times Square",     pay:250,  minRating:40,  icon:"🚕", dept:"transit",  taskType:"click", desc:"Pick up fares across the city. React to each passenger!" },
  { id:"cook",               title:"LINE COOK",           location:"Astoria",            pay:270,  minRating:45,  icon:"👨‍🍳",dept:"food",    taskType:"click", desc:"Prep orders for a packed house. Keep timing tight!" },
  // Professional (100–250 rep)
  { id:"fdny",               title:"FIREFIGHTER (FDNY)",  location:"South Bronx",        pay:350,  minRating:60,  icon:"🚒", dept:"emergency",taskType:"fire",  desc:"Put out fires and save lives. Hit water streams on the flames!" },
  { id:"nypd",               title:"NYPD OFFICER",        location:"Times Square",       pay:320,  minRating:60,  icon:"👮", dept:"police",  taskType:"click", desc:"Patrol the streets. Respond to incidents fast!" },
  { id:"emt",                title:"EMT / PARAMEDIC",     location:"Bellevue Hospital",  pay:300,  minRating:55,  icon:"🚑", dept:"emergency",taskType:"click", desc:"Respond to emergencies across the city. Every second counts!" },
  { id:"teacher",            title:"NYC TEACHER",         location:"Columbia University",pay:310,  minRating:55,  icon:"📚", dept:"education",taskType:"click", desc:"Engage your students. Keep classroom energy high!" },
  { id:"stockbroker_jr",     title:"JUNIOR BROKER",       location:"Wall Street",        pay:460,  minRating:70,  icon:"📊", dept:"finance", taskType:"click", desc:"Execute trades in volatile markets. React to buy/sell signals!" },
  { id:"manager",            title:"FLOOR MANAGER",       location:"Flatiron Building",  pay:560,  minRating:75,  icon:"📋", dept:"mgmt",    taskType:"click", desc:"Handle customer escalations and staff issues!" },
  { id:"nurse",              title:"REGISTERED NURSE",    location:"Bellevue Hospital",  pay:420,  minRating:65,  icon:"👩‍⚕️",dept:"medical", taskType:"click", desc:"Care for patients. Respond to call bells fast!" },
  // Expert (250–500 rep)
  { id:"marketing",          title:"MARKETING EXEC",      location:"Rockefeller Center", pay:720,  minRating:100, icon:"📢", dept:"media",   taskType:"click", desc:"Pitch campaigns to demanding clients!" },
  { id:"realtor",            title:"REAL ESTATE BROKER",  location:"Upper East Side",    pay:950,  minRating:120, icon:"🏠", dept:"realty",  taskType:"click", desc:"Close deals with wealthy clients!" },
  { id:"lawyer",             title:"CORPORATE LAWYER",    location:"Midtown East",       pay:1100, minRating:130, icon:"⚖️", dept:"legal",   taskType:"click", desc:"Win cases before the clock runs out!" },
  { id:"architect",          title:"ARCHITECT",           location:"Flatiron Building",  pay:900,  minRating:120, icon:"📐", dept:"design",  taskType:"click", desc:"Design buildings for demanding clients!" },
  { id:"news_anchor",        title:"TV NEWS ANCHOR",      location:"Rockefeller Center", pay:1200, minRating:140, icon:"📺", dept:"media",   taskType:"click", desc:"Deliver live news under pressure!" },
  // Elite (500–800 rep)
  { id:"finance",            title:"FINANCE ANALYST",     location:"Wall Street",        pay:1500, minRating:200, icon:"💹", dept:"finance", taskType:"click", desc:"Analyze market movements. Execute with precision!" },
  { id:"surgeon",            title:"SURGEON",             location:"Bellevue Hospital",  pay:2000, minRating:250, icon:"🔬", dept:"medical", taskType:"click", desc:"Operate under pressure. Precision is life or death!" },
  { id:"hedge_fund",         title:"HEDGE FUND MANAGER",  location:"Wall Street",        pay:5000, minRating:300, icon:"💰", dept:"finance", taskType:"click", desc:"Manage billions. Every trade matters!" },
  // NYC Legends (800+ rep)
  { id:"exec",               title:"C-SUITE EXECUTIVE",   location:"5th Avenue Shopping",pay:2500, minRating:400, icon:"👔", dept:"mgmt",    taskType:"click", desc:"Lead the boardroom. Handle crises and make power moves!" },
  { id:"real_estate_mogul",  title:"REAL ESTATE MOGUL",   location:"Upper East Side",    pay:8000, minRating:500, icon:"🏰", dept:"realty",  taskType:"click", desc:"Acquire properties across the five boroughs!" },
  { id:"mayor",              title:"NYC MAYOR (CAMPAIGN)", location:"City Hall",         pay:500,  minRating:700, icon:"🏛️", dept:"govt",    taskType:"click", desc:"Run for mayor. Win votes from all five boroughs!" },
  { id:"ceo_startup",        title:"TECH STARTUP CEO",    location:"DUMBO",              pay:3000, minRating:350, icon:"🚀", dept:"tech",    taskType:"click", desc:"Scale your startup. Close deals and ship fast!" },
  { id:"celebrity_chef",     title:"CELEBRITY CHEF",      location:"Chelsea Market",     pay:2200, minRating:280, icon:"⭐", dept:"food",    taskType:"click", desc:"Host your cooking show. Plate dishes perfectly!" },
];

// ── HOUSING DATA ─────────────────────────────────────────────────────
const HOUSING = [
  { id:"shelter",    name:"Homeless Shelter",         location:"South Bronx",      weeklyRent:0,    buyPrice:0,      canBuy:false, icon:"🏚️",  tier:0, ratingEffect: -2 },
  { id:"hostel",     name:"Queens Hostel Bed",         location:"Jackson Heights",  weeklyRent:150,  buyPrice:0,      canBuy:false, icon:"🛏️",  tier:1, ratingEffect: 0  },
  { id:"bronx_studio",name:"Bronx Studio Apt",        location:"South Bronx",      weeklyRent:280,  buyPrice:0,      canBuy:false, icon:"🏠",  tier:2, ratingEffect: 2  },
  { id:"brooklyn_room",name:"Flatbush Bedroom",       location:"Flatbush",         weeklyRent:380,  buyPrice:0,      canBuy:false, icon:"🏘️", tier:3, ratingEffect: 3  },
  { id:"queens_1br",  name:"Astoria 1BR Apartment",   location:"Astoria",          weeklyRent:520,  buyPrice:120000, canBuy:true,  icon:"🏡",  tier:4, ratingEffect: 5  },
  { id:"bk_1br",      name:"Williamsburg 1BR",         location:"Williamsburg",     weeklyRent:580,  buyPrice:160000, canBuy:true,  icon:"🏡",  tier:4, ratingEffect: 5  },
  { id:"harlem_studio",name:"Harlem Studio",          location:"Harlem",           weeklyRent:650,  buyPrice:180000, canBuy:true,  icon:"🏢",  tier:5, ratingEffect: 7  },
  { id:"dumbo_loft",  name:"DUMBO Loft",               location:"DUMBO",            weeklyRent:900,  buyPrice:350000, canBuy:true,  icon:"🏗️",  tier:5, ratingEffect: 8  },
  { id:"uws_1br",     name:"Upper West Side 1BR",      location:"Upper West Side",  weeklyRent:950,  buyPrice:400000, canBuy:true,  icon:"🏢",  tier:6, ratingEffect: 10 },
  { id:"greenwich_2br",name:"Greenwich Village 2BR",  location:"West Village",     weeklyRent:1400, buyPrice:650000, canBuy:true,  icon:"🏠",  tier:6, ratingEffect: 12 },
  { id:"tribeca_loft",name:"Tribeca Loft",             location:"Tribeca",          weeklyRent:2200, buyPrice:900000, canBuy:true,  icon:"🏙️",  tier:7, ratingEffect: 15 },
  { id:"ues_luxury",  name:"Upper East Side Luxury",   location:"Upper East Side",  weeklyRent:2500, buyPrice:1200000,canBuy:true,  icon:"🏰",  tier:8, ratingEffect: 18 },
  { id:"cpw_classic", name:"Central Park West Classic",location:"Upper West Side",  weeklyRent:4000, buyPrice:3000000,canBuy:true,  icon:"🏛️", tier:9, ratingEffect: 22 },
  { id:"fifth_penthouse",name:"Fifth Ave Penthouse",  location:"5th Avenue Shopping",weeklyRent:8000,buyPrice:12000000,canBuy:true, icon:"👑",  tier:10,ratingEffect: 30 },
];

// ── VEHICLES ─────────────────────────────────────────────────────────
const VEHICLES = [
  { id:"bike",        name:"Used Bicycle",      icon:"🚲", price:200,    maintenance:10,   speed:1.5, status:"available" },
  { id:"moped",       name:"Electric Moped",    icon:"🛵", price:1200,   maintenance:30,   speed:2.0, status:"available" },
  { id:"civic",       name:"Honda Civic",        icon:"🚗", price:8000,   maintenance:80,   speed:3.0, status:"available" },
  { id:"corolla",     name:"Toyota Corolla",     icon:"🚗", price:9500,   maintenance:75,   speed:3.0, status:"available" },
  { id:"bmw3",        name:"BMW 3 Series",       icon:"🚙", price:35000,  maintenance:250,  speed:4.0, status:"available" },
  { id:"tesla",       name:"Tesla Model 3",      icon:"🚙", price:42000,  maintenance:120,  speed:4.5, status:"available" },
  { id:"mercedes",    name:"Mercedes S-Class",   icon:"🚗", price:85000,  maintenance:500,  speed:5.0, status:"available" },
  { id:"lambo",       name:"Lamborghini Huracán",icon:"🏎️", price:220000, maintenance:2000, speed:7.0, status:"available" },
  { id:"ferrari",     name:"Ferrari 488",        icon:"🏎️", price:280000, maintenance:2500, speed:7.5, status:"available" },
  { id:"taxi_license",name:"NYC Taxi License",   icon:"🚕", price:15000,  maintenance:300,  speed:3.5, status:"available", special:"taxi" },
  { id:"limo",        name:"Stretch Limousine",  icon:"🚌", price:90000,  maintenance:600,  speed:2.5, status:"available", special:"limo" },
  { id:"yacht",       name:"Hudson River Yacht", icon:"🛥️", price:500000, maintenance:5000, speed:2.0, status:"available", special:"water" },
];

// ── SHOP ITEMS ────────────────────────────────────────────────────────
const SHOP_ITEMS = [
  // TRANSIT
  { id:"metro_single",  name:"Single Ride MetroCard",   icon:"🎫", price:2.90,  cat:"transit",  effect:"metro_single",   desc:"One subway or bus ride" },
  { id:"metro_30day",   name:"30-Day Unlimited Metro",   icon:"💳", price:132,   cat:"transit",  effect:"metro_30day",    desc:"Unlimited rides for 30 days. +5 rating." },
  { id:"cab_ride",      name:"Taxi Ride",                icon:"🚕", price:18,    cat:"transit",  effect:"travel",         desc:"Fast travel anywhere, no MetroCard needed" },
  { id:"uber",          name:"Rideshare",                icon:"🚗", price:24,    cat:"transit",  effect:"travel",         desc:"Door-to-door premium service" },
  // FOOD & DRINK
  { id:"water",         name:"Bodega Water",             icon:"💧", price:1,     cat:"food",     effect:"rating+2",       desc:"Stay hydrated. +2 rating." },
  { id:"coffee",        name:"Bodega Coffee",            icon:"☕", price:1.75,  cat:"food",     effect:"rating+5",       desc:"NYC fuel. +5 rating for the day." },
  { id:"bagel",         name:"Bagel & Lox",              icon:"🥯", price:5,     cat:"food",     effect:"rating+4",       desc:"+4 morale" },
  { id:"pizza",         name:"Dollar Pizza Slice",        icon:"🍕", price:2.50,  cat:"food",     effect:"rating+3",       desc:"Classic NYC fuel. +3 rating." },
  { id:"hot_dog",       name:"Street Hot Dog",           icon:"🌭", price:3.50,  cat:"food",     effect:"rating+3",       desc:"Quick energy. +3 rating." },
  { id:"katz_sandwich", name:"Katz's Pastrami",          icon:"🥪", price:24,    cat:"food",     effect:"rating+10",      desc:"NYC legend sandwich. +10 morale!" },
  { id:"steakhouse",    name:"Peter Luger Steak",        icon:"🥩", price:85,    cat:"food",     effect:"rating+15",      desc:"Best steak in NYC. +15 morale!" },
  { id:"night_out",     name:"Night Out in the City",    icon:"🍾", price:150,   cat:"lifestyle",effect:"morale",         desc:"+15 morale, worth every dollar." },
  // CLOTHING / WARDROBE
  { id:"tshirt",        name:"Basic T-Shirt",            icon:"👕", price:15,    cat:"clothing", effect:"ward+1",         desc:"Casual look.", slot:"top",    img:"👕" },
  { id:"sneakers_bas",  name:"Basic Sneakers",           icon:"👟", price:45,    cat:"clothing", effect:"ward+2",         desc:"+2 rating.", slot:"shoes",  img:"👟" },
  { id:"nike_sneakers", name:"Nike Air Force 1s",        icon:"👟", price:120,   cat:"clothing", effect:"ward+5",         desc:"+5 rating. Iconic.",slot:"shoes",img:"👟" },
  { id:"jeans",         name:"Levi's Jeans",             icon:"👖", price:60,    cat:"clothing", effect:"ward+3",         desc:"+3 rating.", slot:"bottom", img:"👖" },
  { id:"suit_basic",    name:"Basic Business Suit",      icon:"👔", price:120,   cat:"clothing", effect:"ward+10",        desc:"+10 rating permanently.", slot:"suit" },
  { id:"suit_nice",     name:"Brooks Brothers Suit",     icon:"🎩", price:450,   cat:"clothing", effect:"ward+20",        desc:"+20 rating permanently.", slot:"suit" },
  { id:"suit_luxury",   name:"Tom Ford Custom Suit",     icon:"🎩", price:2500,  cat:"clothing", effect:"ward+40",        desc:"+40 rating. Power move.", slot:"suit" },
  { id:"gucci_loafers", name:"Gucci Loafers",            icon:"👞", price:800,   cat:"clothing", effect:"ward+15",        desc:"+15 rating. Flex.", slot:"shoes" },
  { id:"rolex",         name:"Rolex Submariner",         icon:"⌚", price:12000, cat:"clothing", effect:"ward+25",        desc:"+25 rating. Wall St standard.", slot:"watch" },
  { id:"briefcase",     name:"Leather Briefcase",        icon:"💼", price:200,   cat:"clothing", effect:"ward+15",        desc:"+15 rating permanently.", slot:"bag" },
  { id:"hermes_bag",    name:"Hermès Birkin Bag",        icon:"👜", price:25000, cat:"clothing", effect:"ward+35",        desc:"+35 rating. NYC status symbol.", slot:"bag" },
  { id:"streetwear",    name:"Supreme Hoodie",           icon:"🧥", price:300,   cat:"clothing", effect:"ward+8",         desc:"+8 rating. Street cred.", slot:"top" },
  // GEAR
  { id:"cell_phone",    name:"Smartphone",               icon:"📱", price:150,   cat:"gear",     effect:"unlock+5",       desc:"Get job alerts, rideshare. +5 rating." },
  { id:"laptop",        name:"MacBook Air",              icon:"💻", price:1100,  cat:"gear",     effect:"unlock+15",      desc:"Unlocks tech/office jobs. +15 rating." },
  { id:"camera",        name:"Professional Camera",      icon:"📷", price:1800,  cat:"gear",     effect:"unlock+10",      desc:"Freelance photography. +10 rating." },
  { id:"gym",           name:"NYSC Gym Membership",     icon:"💪", price:65,    cat:"lifestyle",effect:"rating+3pw",      desc:"+3 rating/week, health boost." },
  { id:"networking",    name:"Industry Networking Event",icon:"🤝", price:50,    cat:"career",   effect:"rating+10",      desc:"+10 rating, make power contacts." },
  { id:"resume_svc",    name:"Professional Resume",      icon:"📄", price:90,    cat:"career",   effect:"rating+15",      desc:"+15 rating permanently." },
  { id:"mba_course",    name:"Evening MBA Course",       icon:"🎓", price:500,   cat:"career",   effect:"rating+30",      desc:"+30 rating. Serious investment." },
  { id:"therapy",       name:"Therapy Session",          icon:"🛋️", price:200,  cat:"lifestyle",effect:"rating+8",        desc:"+8 wellbeing. Good for the grind." },
  { id:"book",          name:"Business Book",            icon:"📚", price:18,    cat:"career",   effect:"rating+5",       desc:"+5 rating over time." },
  { id:"parking_spot",  name:"Monthly Parking Spot",     icon:"🅿️", price:450,  cat:"transit",  effect:"parking",        desc:"Required if you own a car in Manhattan." },
];

// ── STOCKS ────────────────────────────────────────────────────────────
const STOCKS_DATA = [
  { id:"NYCM", name:"Metro Transit Corp",      sector:"Transit",    basePrice:42,   volatility:0.03, trend:0 },
  { id:"BRKLN",name:"Brooklyn REIT",           sector:"Real Estate",basePrice:88,   volatility:0.05, trend:0.01 },
  { id:"WALL", name:"Wall St Finance Group",   sector:"Finance",    basePrice:156,  volatility:0.07, trend:0.02 },
  { id:"NYRE", name:"NY Real Estate Trust",    sector:"Real Estate",basePrice:214,  volatility:0.06, trend:0.01 },
  { id:"NYTK", name:"Silicon Alley Tech",      sector:"Tech",       basePrice:320,  volatility:0.09, trend:0.03 },
  { id:"MEDIA",name:"Times Square Media Co",   sector:"Media",      basePrice:67,   volatility:0.05, trend:0 },
  { id:"FOOD", name:"NYC Restaurant Group",    sector:"Food/Bev",   basePrice:45,   volatility:0.04, trend:0.01 },
  { id:"HLTH", name:"Manhattan Health Corp",   sector:"Healthcare", basePrice:178,  volatility:0.04, trend:0.015 },
  { id:"LUXRY",name:"Fifth Avenue Luxury Co",  sector:"Retail",     basePrice:540,  volatility:0.06, trend:0.02 },
  { id:"ENRGY",name:"NYC Green Energy",        sector:"Energy",     basePrice:93,   volatility:0.05, trend:0.025 },
];

// ── NPC ENCOUNTERS ────────────────────────────────────────────────────
const NPC_ENCOUNTERS = [
  { name:"Marcus Chen",        type:"WALL STREET WOLF",        emoji:"💼", ratingBoost:7,  isKaren:false,
    lines:["Kid, in this city you either eat or get eaten.","My suit costs more than your monthly rent.","I started in the mailroom. Now? Corner office on the 40th floor."] },
  { name:"Rosa Delgado",       type:"BODEGA OWNER",             emoji:"🏪", ratingBoost:4,  isKaren:false,
    lines:["I came here with $200 and a dream. Thirty years later — three bodegas.","The city will test you every single day. Don't break.","Show up early. Stay late. That's the whole game."] },
  { name:"Tyler Walsh",        type:"HEDGE FUND BRO",           emoji:"🍾", ratingBoost:5,  isKaren:false,
    lines:["My Hamptons house is bigger than this whole block, bro.","Networking is literally everything. You on LinkedIn?","Let me explain compound interest real quick..."] },
  { name:"Maya Patel",         type:"COLUMBIA GRAD STUDENT",    emoji:"🎓", ratingBoost:8,  isKaren:false,
    lines:["Education is the great equalizer. But so is hustle.","NYU rejected me too. Now I'm getting my PhD.","Read 'The Defining Decade' — seriously life-changing."] },
  { name:"Darnell Jackson",    type:"SANITATION WORKER",        emoji:"🗑️", ratingBoost:3,  isKaren:false,
    lines:["This city is BUILT on people like us. Don't forget it.","I work nights so my kids can go to school days.","Respect everyone. You never know who knows who."] },
  { name:"Victoria Sterling",  type:"UPPER EAST SIDE SOCIALITE",emoji:"👑", ratingBoost:9,  isKaren:false,
    lines:["Darling, your shoes... are those from Target?","My father knows the CEO of Goldman. Do you have contacts?","Image is *everything* in this city. Invest. In. Yourself."] },
  { name:"Jimmy Two-Dogs",     type:"BRONX HUSTLER",            emoji:"🎲", ratingBoost:2,  isKaren:false,
    lines:["Yo, you need anything — you come to Jimmy. Anything.","Nah nah stay legal. The city got cameras everywhere now.","My cousin knows a guy who's hiring. No, seriously though."] },
  { name:"Raj Anand",          type:"TECH STARTUP FOUNDER",     emoji:"🚀", ratingBoost:10, isKaren:false,
    lines:["Series A just closed. Absolutely wild ride.","The best time to start was yesterday. Second best is today.","Silicon Alley is real — NYC tech is actually exploding right now."] },
  { name:"Old Man Sal",        type:"RETIRED LONGSHOREMAN",      emoji:"⚓", ratingBoost:4,  isKaren:false,
    lines:["I unloaded ships at Red Hook for 40 years. Honest work.","New York ain't what it was. But opportunity? Still here.","Young person, the secret is: never stop moving."] },
  { name:"Sandra Kim",         type:"KOREAN-AMERICAN CHEF",     emoji:"👩‍🍳",ratingBoost:6,  isKaren:false,
    lines:["I opened my restaurant on this block seven years ago. Never left.","Korean food is taking over NYC — we just needed the space.","Work hard, but eat harder. Food is community."] },
  { name:"Kevin Okafor",       type:"NYPD DETECTIVE",           emoji:"🕵️", ratingBoost:5,  isKaren:false,
    lines:["I've been on the force for 20 years. This city never sleeps.","Stay out of trouble. The precinct doesn't forget faces.","There's opportunity in this city — but also consequence."] },
  // KARENS — special NPC type
  { name:"Karen M.",           type:"⚠️ CLASSIC KAREN",         emoji:"😤", ratingBoost:-8, isKaren:true,
    lines:["I want to speak to your MANAGER right NOW.","This is unacceptable! I'm calling corporate!","Do you even know who I am? I will LEAVE a review."] },
  { name:"Patricia B.",        type:"⚠️ MANAGEMENT KAREN",      emoji:"😤", ratingBoost:-6, isKaren:true,
    lines:["Is THIS how you treat paying customers?!","I've been coming here for YEARS and this is what I get?","I'm going to blast this on Yelp. Just so you know."] },
  { name:"Chad W.",            type:"⚠️ MALE KAREN (KYLE)",     emoji:"😤", ratingBoost:-5, isKaren:true,
    lines:["Excuse me? Do you know how much I make per year?","My lawyer will be hearing about this.","I went to Wharton. I know my rights."] },
];

// ── RANDOM EVENTS ─────────────────────────────────────────────────────
const RANDOM_EVENTS = [
  { id:"found_wallet",   title:"FOUND WALLET",         emoji:"👛",
    desc:"You found a wallet on the subway platform with $65 inside. What do you do?",
    choices:[
      { text:"Keep the cash",                          effect:(G)=>{ G.cash+=65; G.rating-=5; return "Kept the cash. Quick $65. Feels off though. -5 rep."; }},
      { text:"Turn it in to MTA Lost & Found",         effect:(G)=>{ G.rating+=12; return "Turned in the wallet. MTA officer was impressed. +12 rep!"; }},
    ]},
  { id:"rain",           title:"SUDDEN DOWNPOUR",      emoji:"🌧️",
    desc:"Classic NYC thunderstorm hits with zero warning. Streets flood instantly.",
    choices:[
      { text:"Buy umbrella from vendor ($8)",          effect:(G)=>{ G.cash-=8; return "Bought a $8 bodega umbrella. Survived."; }},
      { text:"Get soaked — you're built different",    effect:(G)=>{ G.rating-=6; return "Arrived SOAKED. Boss was not impressed. -6 rep."; }},
      { text:"Wait it out in a coffee shop ($5)",      effect:(G)=>{ G.cash-=5; G.hour+=1; return "Waited it out. Cost an hour but stayed dry."; }},
    ]},
  { id:"rent_hike",      title:"RENT HIKE NOTICE",     emoji:"📬",
    desc:"Landlord slides a note under the door. Rent going up 18% next month.",
    choices:[
      { text:"Accept it (you need the place)",         effect:(G)=>{ G.rentPerWeek=Math.floor(G.rentPerWeek*1.18); return "Rent went up. Welcome to NYC."; }},
      { text:"Negotiate — you're confident now",       effect:(G)=>{ if(G.rating>=80){return "Your confidence worked. Rent stays the same!";}else{G.rentPerWeek=Math.floor(G.rentPerWeek*1.18);return "He laughed. Raised it anyway.";}; }},
    ]},
  { id:"job_offer",      title:"UNEXPECTED OPPORTUNITY",emoji:"📇",
    desc:"Someone at a networking event hands you a card. 'We've heard about you. We have an opening.'",
    choices:[
      { text:"Accept the meeting",                     effect:(G)=>{ G.rating+=15; return "Took the meeting. Incredible connections. +15 rep!"; }},
      { text:"Play it cool",                           effect:(G)=>{ G.rating+=7; return "Left a great impression. +7 rep."; }},
    ]},
  { id:"subway_delay",   title:"SUBWAY NIGHTMARE",     emoji:"🚇",
    desc:"Signal problems at Jay St. You're stuck underground. You WILL be late.",
    choices:[
      { text:"Suffer through it",                      effect:(G)=>{ G.rating-=7; return "45-min delay. Arrived late. Boss is not happy. -7 rep."; }},
      { text:"Grab a cab ($20)",                       effect:(G)=>{ if(G.cash>=20){G.cash-=20;return "Took a $20 cab and made it on time!";}else{G.rating-=7;return "No cab money. Stuck in the tunnel.";}; }},
    ]},
  { id:"mugged",         title:"GETTING MUGGED",       emoji:"⚠️",
    desc:"Late in Midtown. Someone demands your wallet. Heart pounding.",
    choices:[
      { text:"Hand over cash ($30-80)",                effect:(G)=>{ const l=Math.min(G.cash,30+Math.floor(Math.random()*50));G.cash-=l;return `Gave them $${l}. Staying safe was the call.`; }},
      { text:"Run for it",                             effect:(G)=>{ if(Math.random()>0.45){return "SPRINTED. Made it clean!";}else{const l=Math.min(G.cash,70);G.cash-=l;return `Couldn't outrun them. Lost $${l}.`;}; }},
      { text:"Stand your ground (risky)",              effect:(G)=>{ if(G.rating>=80){G.rating+=5;return "You stood tall. They backed off. +5 rep for the bravery.";}else{const l=Math.min(G.cash,100);G.cash-=l;G.rating-=5;return `Bad idea. Lost $${l} and -5 rep.`;}; }},
    ]},
  { id:"overtime",       title:"OVERTIME OFFER",       emoji:"⏰",
    desc:"Boss: 'Can you stay late? Double pay for 4 extra hours.'",
    choices:[
      { text:"Stay for overtime",                      effect:(G)=>{ const b=G.job?G.job.pay:60;G.cash+=b;G.rating+=8;return `Worked overtime! +$${b} bonus, +8 rep!`; }},
      { text:"Decline — you need rest",                effect:(G)=>{ return "Went home. Rest is important."; }},
    ]},
  { id:"invest_tip",     title:"PENNY STOCK TIP",      emoji:"📈",
    desc:"Guy on the subway loudly explains a stock is 'guaranteed to 10x.' Very convincing. Suspicious.",
    choices:[
      { text:"Invest $200 (gamble!)",                  effect:(G)=>{ if(G.cash>=200){G.cash-=200;if(Math.random()>0.55){G.cash+=700;return "IT PUMPED!! You're up $500!"}else{return "Rug pulled. Lost $200. That guy scammed you.";};}else{return "Not enough cash.";}; }},
      { text:"Ignore it",                              effect:(G)=>{ return "Smart. Almost definitely a scam."; }},
    ]},
  // KAREN EVENTS
  { id:"karen_job",      title:"KAREN AT WORK",        emoji:"😤",
    desc:"A customer is LOSING IT because they waited 3 extra minutes. They're demanding your manager.",
    choices:[
      { text:"Stay calm & professional",               effect:(G)=>{ G.rating+=5; return "Kept your composure. Manager was impressed. +5 rep."; }},
      { text:"Get the manager immediately",            effect:(G)=>{ return "Deescalated. No damage done."; }},
      { text:"Argue back (not recommended)",           effect:(G)=>{ G.rating-=12; return "You argued with the Karen. Big mistake. -12 rep."; }},
    ]},
  { id:"karen_street",   title:"KAREN BLOCKS YOUR PATH",emoji:"😤",
    desc:"A woman is blocking the entire sidewalk and yelling at you for 'almost bumping into her.'",
    choices:[
      { text:"Apologize and keep moving",              effect:(G)=>{ return "Took the high road. Smart."; }},
      { text:"Record the interaction on your phone",   effect:(G)=>{ G.rating+=3; return "This might go viral. +3 rep."; }},
      { text:"Argue back",                             effect:(G)=>{ G.rating-=4; return "Not worth it. -4 rep."; }},
    ]},
  // POLICE EVENTS
  { id:"police_stop",    title:"NYPD STOP",            emoji:"👮",
    desc:"A police officer stops you. 'License and registration' (or ID). You were jaywalking.",
    choices:[
      { text:"Cooperate fully",                        effect:(G)=>{ G.cash-=75; return "Paid the $75 jaywalking ticket. Clean record kept."; }},
      { text:"Talk your way out of it",                effect:(G)=>{ if(G.rating>=70){return "They let you go with a warning. Rep helped.";}else{G.cash-=75;return "Didn't work. $75 fine.";} }},
    ]},
  // FIRE EVENT
  { id:"fire_nearby",    title:"BUILDING FIRE!",       emoji:"🔥",
    desc:"Smoke pours out of a nearby building. You hear people inside.",
    choices:[
      { text:"Call 911 and wait",                      effect:(G)=>{ G.rating+=6; return "FDNY arrives in minutes. You helped. +6 rep."; }},
      { text:"Help evacuate (if FDNY job)",            effect:(G)=>{ if(G.job&&G.job.dept==='emergency'){G.rating+=20;G.cash+=200;return "Hero response. +20 rep, $200 bonus!";} else {G.rating+=10;return "Helped people out. +10 rep.";} }},
    ]},
  // BONUS EVENTS
  { id:"street_art",     title:"VIRAL STREET ART",     emoji:"🎨",
    desc:"Someone spray-painted a mural of YOU on a building in Brooklyn. It's going viral.",
    choices:[
      { text:"Embrace it — post on social media",      effect:(G)=>{ G.rating+=15; return "You're NYC famous now. +15 rep!"; }},
      { text:"Ask them to take it down",               effect:(G)=>{ return "They refused anyway. It's still there."; }},
    ]},
  { id:"lotto_win",      title:"SCRATCH TICKET",       emoji:"🎰",
    desc:"You bought a $5 scratch ticket from a bodega. There's a winner...",
    choices:[
      { text:"Scratch it",                             effect:(G)=>{ G.cash-=5; const r=Math.random(); if(r>0.95){G.cash+=1000;return "WON $1000!! BODEGA MIRACLE!"}else if(r>0.8){G.cash+=20;return "Won $20. Small W."}else{return "Nothing. Story of New York.";}; }},
      { text:"Save it for later",                      effect:(G)=>{ return "Pocket it for now."; }},
    ]},
  { id:"taxi_dispute",   title:"CAB DISPUTE",          emoji:"🚕",
    desc:"Cab driver took a way longer route. Meter hit $42 instead of the normal $18.",
    choices:[
      { text:"Pay the full fare",                      effect:(G)=>{ G.cash-=42; return "Paid up. Lesson learned."; }},
      { text:"Dispute it and offer $20",               effect:(G)=>{ if(G.rating>=60){G.cash-=20;return "Driver respected your confidence. Paid $20.";} else {G.cash-=42;return "No leverage. Paid full $42.";}; }},
    ]},
];

// ── ACHIEVEMENTS ──────────────────────────────────────────────────────
const ACHIEVEMENTS = [
  { id:"first_job",   title:"FIRST HUSTLE",     desc:"Get your first job",              reward:5,   check:(G)=>G.resume.length>0||G.job!=null },
  { id:"100rep",      title:"THREE DIGITS",     desc:"Reach 100 reputation",            reward:20,  check:(G)=>G.rating>=100 },
  { id:"250rep",      title:"RISING STAR",      desc:"Reach 250 reputation",            reward:50,  check:(G)=>G.rating>=250 },
  { id:"500rep",      title:"CITY LEGEND",      desc:"Reach 500 reputation",            reward:100, check:(G)=>G.rating>=500 },
  { id:"1000rep",     title:"NYC ICON",         desc:"Reach 1000 reputation",           reward:500, check:(G)=>G.rating>=1000 },
  { id:"millionaire", title:"THE MILLION",      desc:"Cash + Savings = $1,000,000",     reward:200, check:(G)=>(G.cash+G.savings)>=1000000 },
  { id:"homeowner",   title:"PROPERTY OWNER",  desc:"Buy your first property",         reward:100, check:(G)=>G.ownedHomes.length>0 },
  { id:"car_owner",   title:"WHEELIN'",         desc:"Own your first vehicle",          reward:30,  check:(G)=>G.vehicles.length>0 },
  { id:"stockgain",   title:"WALL ST MOVE",     desc:"Make $500+ from stocks",          reward:50,  check:(G)=>G.totalStockGains>=500 },
  { id:"day30",       title:"MONTH IN THE CITY",desc:"Survive 30 days in NYC",         reward:30,  check:(G)=>G.day>=30 },
  { id:"day100",      title:"100 DAYS HUSTLE",  desc:"Survive 100 days in NYC",        reward:100, check:(G)=>G.day>=100 },
  { id:"karen_king",  title:"KAREN SLAYER",     desc:"Handle 5 Karens professionally", reward:25,  check:(G)=>G.karensHandled>=5 },
  { id:"fire_hero",   title:"FDNY RESPECT",     desc:"Complete a fire emergency",       reward:40,  check:(G)=>G.firesHandled>=1 },
];
